# Generated by Django 4.2 on 2023-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('total', models.IntegerField()),
                ('avg', models.DecimalField(decimal_places=17, max_digits=20)),
                ('max', models.DecimalField(decimal_places=17, max_digits=20)),
                ('min', models.DecimalField(decimal_places=17, max_digits=20)),
                ('sumD', models.IntegerField()),
                ('Ourl', models.CharField(max_length=255)),
                ('Purl', models.CharField(max_length=255)),
            ],
        ),
    ]
